### ISSUE TITLE
Mclighting on ESP03 with upgraded Flash

### ISSUE THREAD

**Issue by huge-11** [FabLab-Luenen/McLighting#101]
Hello, 
i am trying to use a mclighting on a ESP03 with a 32mbit flash chip.
I somehow cannot acces the AP from my android phone, so itried on my pc. Sometimes it works on the pc sometimes it does not. Once i manage to enter the SSID and PWD, i cannot get a connection betwenn my router and the esp. Sometimes it takes ages to load the AP config site. 
Any help is welcome

**Comment by bpohvoodoo** [comment]
I can't see how i can help you without further information, like espstatus and console infos.
