### ISSUE TITLE
Strip GPIO Pin

### ISSUE THREAD

**Issue by Alveran81** [FabLab-Luenen/McLighting#104]
I can not change Strip GPIO Pin in WebUI. Its allways Pin 3
How Can I change it?

Otherwise what ist PIN 3 on a NODEMCU?

**Comment by bpohvoodoo** [comment]
See 
#define USE_WS2812FX_DMA 0      // 0 = Used PIN is ignored & set to RX/GPIO3; 1 = Used PIN is ignored & set to TX/GPIO1; 2 = Used PIN is ignored & set to D4/GPIO2;  Uses WS2812FX, see: https://github.com/kitesurfer1404/WS2812FX
                                // or comment it out
