### ISSUE TITLE
New OFF implementation for HTTP API Causes Reboot

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#107]
When requesting off from the HTTP API, now the boar simply locks up and reboots after a few seconds.  Is there some type of change to the settings that I have to make to get it to work?
I am getting an NOK response and nothing shows up in the terminal window.  So, it appears that State.mode is not actually "set".  Also, "on" doesn't work correctly.  It appears that it's using prevmode instead of State.mode?  
Funny part is, now the only option from the HTTP API is toggle.  :-)

**Comment by ryancasler** [comment]
Yup...just tested both fixes.  Will send a pull request shortly.

**Comment by bpohvoodoo** [comment]
Is implemented now
