### ISSUE TITLE
WS2801 supported?

### ISSUE THREAD

**Issue by DenisMtfl** [FabLab-Luenen/McLighting#110]
Hello, i have a 6m WS2801 LEDs Strip on Raspberry and now i would like to chose McLighting and an arduino like Wemos D1 mini/pro as an alternative because of power-saving. So my question are the WS2801 also supported on McLighting?

Thanks!

**Comment by bpohvoodoo** [comment]
No, they are not.

**Comment by DenisMtfl** [comment]
But i have found th WS2801FX project !? Is it useable ?

**Comment by bpohvoodoo** [comment]
Yes, but the library is older, and I will not implement it, but you could try.

**Comment by DenisMtfl** [comment]
okay i will
