### ISSUE TITLE
Controlling Segments from the REST API

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#116]
I don't see anything in the documentation of the Wiki how to request command for a specific segment of the strip.  I know you can from the web UI but it's not clear how to do that from the API.  I'm sure it's just another parameter I'm missing but I can't figure it out.  I tried sending the "seg" argument and the mode changed for the selected segment but the colors changed for the other segment.

**Comment by bpohvoodoo** [comment]
seg is the right argument http://ip_of_device/set?seg= 0...9,
but you have to use it stand alone, as it is processed last.

**Comment by ryancasler** [comment]
Thank you!  That was what I was looking for.  I was trying "segment" and couldn't get it to work.  Thanks!!!
