### ISSUE TITLE
RGBW Control in Homeassistant

### ISSUE THREAD

**Issue by DigitalElise** [FabLab-Luenen/McLighting#2]
I have noticed that it is possible to set the white chanel in the RGBW index.htm but it doesn't seem to come across to home assistant.

Are you able to add this to the build or point me in the right direction where to add this functionality to home assistant?

**Comment by bpohvoodoo** [comment]
What exactly is the Problem? Does McLighting RGBW does not send the information to ha or vice versa?
The code for ha should be implemented.

**Comment by bpohvoodoo** [comment]
Fixed now
