### ISSUE TITLE
Is it possible to create gradients?

### ISSUE THREAD

**Issue by VeniceNerd** [FabLab-Luenen/McLighting#25]
Im wondering if it is possible to create gradients with this repository. For example I’d love to set saturated blue on one end of the strip and have it fade to pure white on the other end of the strip. 

No animations or anything. Just a simple gradient fade. Is that doable?

**Comment by bpohvoodoo** [comment]
Feature is in development and already working.

**Comment by VeniceNerd** [comment]
@bpohvoodoo omg are you serious??? That is absolutely incredible!!!! Can't wait for this to ship! Will it support pure white channel as well? So fading from the pure white LED to a mix of colors on the other end?

**Comment by bpohvoodoo** [comment]
Yes, it will, but it could take some time to release, because I have implemented a few other things and there are some problems with those features and my time is very limited.

**Comment by VeniceNerd** [comment]
It’s super cool. Really exciting! Do you think there will be a way to invoke those “fade recipes” in HomeKit as well? Or can they be invoked by a link? I think in that case I could use Apple Shortcuts to automate them into my scenes.

**Comment by VeniceNerd** [comment]
Oh and can I help in any way? I won’t be of any use with programming but I’d be happy to test or discuss ideas. 

Would also be happy to donate to the project if you accept donations.

**Comment by bpohvoodoo** [comment]
If you want you can try the beta branch now. Gradients is a CustomEffect (61).
https://github.com/FabLab-Luenen/McLighting/tree/beta

**Comment by bpohvoodoo** [comment]
If you want you can try the development branch (3.1.0) now. Gradients is a CustomEffect (61).
https://github.com/FabLab-Luenen/McLighting/tree/development
