### ISSUE TITLE
[Homeassistant] "{"brightness":82.5}" have no Funktion

### ISSUE THREAD

**Issue by gitpower2017** [FabLab-Luenen/McLighting#3]
I Controll the McL with MQTT - Homeassistant.

Wen I send "{"brightness":82.5}" have this no funktion.
All other Works good.

z.B. "{"speed":25.5}"

**Comment by bpohvoodoo** [comment]
I take a look

**Comment by bpohvoodoo** [comment]
Fixed. I missed one line of code
Can you check with the latest version?
by the way: the allowed values for both are between 0 and 255 Integer not percent
