### ISSUE TITLE
OTA Not Supported?

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#33]
For some reason, the board doesn't show up as an available network port after using the static IP address even though I have not commented out OTA support.  Any idea what is going on?

**Comment by bpohvoodoo** [comment]
Which OTA do you have enabed?

maybe you try http://ipofyourdevice/update

Here you can upload a bin file.

**Comment by ryancasler** [comment]
Oh...I didn't realize that was an option.  I will give that a try.  

UPDATE:  That works perfectly!!  I didn't know that was the other way to do it.  Wonderful!  Thanks!
