### ISSUE TITLE
What settings are needed for ws2812b

### ISSUE THREAD

**Issue by viktor6** [FabLab-Luenen/McLighting#34]
What settings are needed for ws2812b
I'm newbie sorry

**Comment by ACKET2009** [comment]
GRB... what settings do you need?

**Comment by bpohvoodoo** [comment]
#define RGBORDER "GRB"    // RGBOrder; is configurable just for the start
or change it later:
![image](https://user-images.githubusercontent.com/4918785/64611062-d4e5d080-d3d0-11e9-8e20-1b6b47121d6d.png)

**Comment by viktor6** [comment]
> #define RGBORDER "GRB" // RGBOrder; is configurable just for the start

Thank! I thought so.
