### ISSUE TITLE
Segment Size not Saved on Reboot

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#36]
I have #define ENABLE_STATE_SAVE 1  but it seems that Segment Size from the options is not saved when the board is rebooted.  It continues to revert back to the default small size.  I am using the latest built 2.2.6 and a Wemos D1 Mini board.  It seems that other options (RGB order, Pixel Count, etc) are saving correctly.  Is there a way to "hard code" this into my sketch as a temporary work around?  I tried to find where the option is defined but unfortunately I think it's a couple of layers down further than i'm able to follow.  Thanks!!

**Comment by bpohvoodoo** [comment]
I testet it and can't reproduce. In my case it is always saved. 
For hardcode do use definitions.h
#define FX_OPTIONS 48      // ws2812fx Options 48 = SIZE_SMALL + FADE_MEDIUM  is configurable just for the start;
for WS2812FX setSegment OPTIONS, see: https://github.com/kitesurfer1404/WS2812FX/blob/master/extras/WS2812FX%20Users%20Guide.md

**Comment by bpohvoodoo** [comment]
Ok found the reason. I looked at saving which was fine, but the reading after reboot failed!

**Comment by ryancasler** [comment]
The new fix seems to have resolved the issue.
