### ISSUE TITLE
Web GUI

### ISSUE THREAD

**Issue by joseh55** [FabLab-Luenen/McLighting#38]
Hello Thank you for your Work!
I have a problem... the firts time i used load normaly, but later of upload and accesss the web loading screen appear and and say " 67% loading models", later say 100% Ready and stuck here... 
i recompiled, re downloaded git hub project but no work anymore

any clue or help?
Thank you!

**Comment by bpohvoodoo** [comment]
No problems here try presing CTRL and reload the GUI.
