### ISSUE TITLE
IP address output

### ISSUE THREAD

**Issue by viktor6** [FabLab-Luenen/McLighting#39]
Draw the IP address that the wi-fi detected in Mqtt
This is necessary for the ripening of a smart home in a smart home

**Comment by bpohvoodoo** [comment]
Can you please explain exactly what you mean?

**Comment by viktor6** [comment]
To display information about IP address in this topic
home/McLighting1_ha/state/out
for example
 {"state": "ON",**"ip": "192.168.2.123",**"color": {"r": 255,"g": 0,"b": 0,"w": 0,"r2": 0,"g2": 255,"b2": 0,"w2": 0,"r3": 0,"g3": 0,"b3": 255,"w3": 0},"brightness": 200,"color_temp": 327,"speed": 60,"effect": "AUTO"}

**Comment by bpohvoodoo** [comment]
I do not see why you should need this.

**Comment by viktor6** [comment]
It’s hard to explain, but believe me, this is useful for others.

**Comment by viktor6** [comment]
IP definition does not work
{
  "state" : "ON",
  "ip" : true,
  "color" : {
    "r" : 255,
    "g" : 0,
    "b" : 0,
    "w" : 0,
    "r2" : 0,
    "g2" : 255,
    "b2" : 0,
    "w2" : 0,
    "r3" : 0,
    "g3" : 0,
    "b3" : 255,
    "w3" : 0
  },
  "brightness" : 126,
  "color_temp" : 327,
  "speed" : 122,
  "effect" : "Color Wipe"
}

**Comment by bpohvoodoo** [comment]
I will have a look

**Comment by viktor6** [comment]
Everything is working
