### ISSUE TITLE
RGB-value deletes white-value in homeassistant

### ISSUE THREAD

**Issue by Lagertonne** [FabLab-Luenen/McLighting#44]
**Describe the bug**
If I set the RGB-Value in Homeassistant, it resets a previously set white-value to 0. The white value is adjustable afterwards, and stays at that value.

**To Reproduce**
1. McLighting is autodiscovered by homeassistant
2. Set a white-value
3. Set a RGB-value
4. The white-value goes back to 0 after a few seconds
**Expected behavior**
The white-value should stay the same.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox
 - Version: 69.0.2

**Additional context**
I'm not sure if this is a homeassistant or a McLighting-Bug. But because of the fact that the white-value needs some time until it jumps to 0 and the LEDs turn off instantly, I think it's a McLighting thing.

**Comment by bpohvoodoo** [comment]
This seems not to be a problem of McLighting. Homeassistant sets the white value to 0, but i have to check it.
