### ISSUE TITLE
Customize default index/frontpage

### ISSUE THREAD

**Issue by martindaniel1** [FabLab-Luenen/McLighting#54]
Hi,  so i have figured out how to use everything and got it working with pretty much default settings, but with another amount of leds and pins in use. 

I have installed the "ESp8622 sketch data upload", and changed the index.htm-file within the data-folder and uploaded. But the page wont update on the esp. I want to change language on the page and also some of the colours.

**Comment by bpohvoodoo** [comment]
Then you have to comment out 
#define USE_HTML_MIN_GZ               // uncomment for using index.htm & edit.htm from PROGMEM instead of SPIFFs
in definitions.h, otherwise it will allways use pages from progmem
Which colors do you want to change? Most of them are configurable via settings.
