### ISSUE TITLE
After the playing in single mode, the autoplay mode can not be started

### ISSUE THREAD

**Issue by ACKET2009** [FabLab-Luenen/McLighting#57]
Hello! The version, I use, is latest - beta 5
The autoplay mode starts normally after flashing - it's ok!
While I make any definition on the web interface - m.b. static, after the restart it is always in static mode. And without this string http://192.168.1.6/set?m=56 on the web browser no any choice to start the autoplaying again. There is no switch to toggle off/on autoplay on the web page now. Please return it!

**Comment by ACKET2009** [comment]
Or, may be, make the autoplay mode by default, after each reconnect or reset...

**Comment by bpohvoodoo** [comment]
Try using this (Animation 56):
![image](https://user-images.githubusercontent.com/4918785/68957463-62c3aa80-07ca-11ea-9fab-1b6dbfa2f062.png)
