### ISSUE TITLE
Request to add friendly hostname visibility to DHCP table

### ISSUE THREAD

**Issue by vemeT5ak** [FabLab-Luenen/McLighting#59]
**Is your feature request related to a problem? Please describe.**
No problem. Request 

**Describe the solution you'd like**
Add WiFi.hostname(HOSTNAME); before WiFi.begin on line 730 of McLightning.ino

**Additional context**
This is to simply make it easier to find a specific device IP once it has connected to a local WiFi. I currently have 9 McLightnings deployed at my house and keeping track of them is a task in of itself.

Thank you for your time

**Comment by bpohvoodoo** [comment]
Will check this.
