### ISSUE TITLE
All Light Params in One Request to HTTP API

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#61]
It's possible that this is already working but I could not find a way to retrieve all of the current settings in one HTTP request.  Using the endpoint /all turns them back on if they were previously switched off, so that doesn't really work all that well.  I really don't want to have to go through the trouble of issuing 5 or 6 http calls to get all of the parameters from the board.  Thanks!

**Comment by bpohvoodoo** [comment]
Maybe you want to give /status a try

https://github.com/FabLab-Luenen/McLighting/wiki/HTTP-REST-API-(V3)

**Comment by ryancasler** [comment]
DUH!   We have an expression in the US, "if it was a dog, it would have bit me."  I looked at that page for almost an hour and didn't see it.  Now of course it stands right out.  Thanks for the tip!
