### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by FWeissenb** [FabLab-Luenen/McLighting#65]
**Describe the bug**
I have a 12 LED Ring connected to D4/GND/3.3V and McLighting doesn't boot. 
If I first switch on my power supply and wait for wifi connection and THEN connect my led ring it works like a charm.

**To Reproduce**
see description

**Expected behavior**
Normal boot and wifi connection with connected led ring.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bpohvoodoo** [comment]
D4 is GPIO02 which is the LEDBUILTIN on NodeMCU. Maybe this is causing the problem, because it is used for Status blinking during startup.
Try commenting out digital read & write:
```
void tick() {
  //toggle state
  //uint16_t state = digitalRead(LED_BUILTIN);  // get the current state of GPIO1 pin
  //digitalWrite(LED_BUILTIN, !state);     // set pin to the opposite state
}
```

in McLighting.ino
