### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by TitQuentin** [FabLab-Luenen/McLighting#72]
Hi all.
I get this error when I try to compile the code.
I tried with the recommended versions and the latest version of the libraries and arduino tools.
I also deleted the Arduino15 folder
But nothing works. Do you have an idea?

https://pastebin.com/5ZDthwK8

Thx for help !

**Comment by bpohvoodoo** [comment]
It seems that ESPAsyncTCP.h library is missing.
https://github.com/me-no-dev/ESPAsyncTCP
