### ISSUE TITLE
does an "ESP8266 ESP-12F" or just an "ESP8266 ESP-12E" work?

### ISSUE THREAD

**Issue by KoggeHD** [FabLab-Luenen/McLighting#76]
Hello I want to create a project. But I have no idea whether it must be a 12E or whether a 12F also works.

can someone answer the question?
does an "ESP8266 ESP-12F" or just an "ESP8266 ESP-12E" work?

sorry if I am not allowed to ask here.
However, I don't know where else to ask since I want to use MCLightnig.

greeting Kogge

**Comment by bpohvoodoo** [comment]
Hi there,
both work, as ther are nearly the same,  but i recommend wemos d1 mini or nodemcu boards.
