### ISSUE TITLE
NodeMcu not start

### ISSUE THREAD

**Issue by manuallv** [FabLab-Luenen/McLighting#77]
settings by default. I don't know how to even name this error?
Can anyone help?

1. upload all content. ok. but nothing happens next
![Screenshot_2](https://user-images.githubusercontent.com/12850681/79114971-56e60f80-7d8d-11ea-912c-6f988e0bb61b.png)

2. When restart Nodemcu module then, serial Monitor show me this:
[https://youtu.be/2Ku9qin4zII](https://youtu.be/2Ku9qin4zII)

where could be the problem?

**Comment by bpohvoodoo** [comment]
It seems, that you already used this NodeMCU for Toblums original Project.
Please erase all content with:
![image](https://user-images.githubusercontent.com/4918785/79122642-84848600-7d98-11ea-9781-bf63ca6a4a46.png)

**Comment by manuallv** [comment]
> It seems, that you already used this NodeMCU for Toblums original Project.
> Please erase all content with:
> ![image](https://user-images.githubusercontent.com/4918785/79122642-84848600-7d98-11ea-9781-bf63ca6a4a46.png)

Thanks, everything is working now
