### ISSUE TITLE
Change index file

### ISSUE THREAD

**Issue by manuallv** [FabLab-Luenen/McLighting#78]
Hi, maybe this will be a stupid question, but I can't change the index.htm file. 
I  uncomment #define USE_HTML_MIN_GZ  and upload index.htm file in /upload, but but nothing changes

**Comment by bpohvoodoo** [comment]
If you uncomment this the interanl index.html file will be usesd. To use the spiffs version you have to comment it out.
#define USE_HTML_MIN_GZ               // uncomment for using index.htm & edit.htm from **PROGMEM** instead of **SPIFFS**

**Comment by bpohvoodoo** [comment]
What do you have changed in index.htm?
