### ISSUE TITLE
Using Tags / Releases for new versions

### ISSUE THREAD

**Issue by 19Andy89** [FabLab-Luenen/McLighting#82]
Hello,
in order to use the Github API it would be nice, if you could use Tags or Releases.

so i could check one of these urls:
https://api.github.com/repos/FabLab-Luenen/McLighting/tags
https://api.github.com/repos/FabLab-Luenen/McLighting/releases/latest

I could check these urls once a day automatically and get informed by a system if a new version gets releases or tagged. 

Thanks in advance,
Andreas

**Comment by bpohvoodoo** [comment]
Now with tags and releases
