### ISSUE TITLE
toblum vs FabLab

### ISSUE THREAD

**Issue by perlchamp** [FabLab-Luenen/McLighting#88]
**Is your feature request related to a problem? Please describe.**
i wonder why renewal is getting worse and worse compared to the original. v3 is definitely overloaded. v2 starts quickly and reliably. v3 hangs at 100% or takes minutes to start. less is more !
I will definitely stay with v2 if nothing changes fundamentally with v3!
sometimes v3 hangs completely if you try out lighting effects one after the other without repeatedly clicking off ...
the design is nicer but for me that's just a side effect ... performance first !

**Describe the solution you'd like**
better, faster, more reliable

**Describe alternatives you've considered**
now v2 is untouchable

**Additional context**
good luck

**Comment by bpohvoodoo** [comment]
You can use whatever you want. I do not have any performance issues.
