### ISSUE TITLE
/off HTTP Request When Strip is Off Results in Strip Returning to Last Saved State

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#93]
If a strip is turned off and you issue an http request to /off, the strip will turn on again at the last settings that it was set to.

**Comment by bpohvoodoo** [comment]
It is not that easy. Have to implement your changes to html and to other functions, too, as they use "off" for toogle.

**Comment by ryancasler** [comment]
The fix that was implemented for this doesn't work.  A request to the board for /off, simply causes the board to reboot.
